export const String = {
  LogOut: "Logout",
  LogOutText: "Are you sure you want to Logout?",
  Cancel: "Cancel",
  Ok: "OK",
  Setting: "Settings",
  Down: "DOWN",
  Left: "LEFT",
  Right: "RIGHT",
  Up: "UP",
  ListenMusic: 'Listen to the music,',
  ListenMusicSec: 'feel the pain',
  ListenAny: 'Listen to music anywhere at anytime',
  ColName: 'Album Name',
  RelDate: "Release Date",
  Search: "Search...",
  homeSrchTxt: 'Search your favourite artist here...',
  SearchStr: 'uh-oh! No result for xyz artistname. please try something else.',
  pdHomeSrchTxt: 'Search your favourite podcast here...',
  pdSearchStr: 'uh-oh! No result for xyz podcast episode. please try something else.',
  inroTitle1: "Search your joy through music",
  inroTitle2: "Let music flow in your heart and enrich your soul",
  inroTitle3: "We Bring The Good Podcast To Life",
};
