export const String = {
  LogOut: "Logout",
  LogOutText: "Are you sure you want to Logout?",
  Cancel: "Cancel",
  Ok: "OK",
  Setting: "Settings",
  Down: "DOWN",
  Left: "LEFT",
  Right: "RIGHT",
  Up: "UP",
  ListenMusic: "Listen to the music,",
  ListenMusicSec: "feel the pain",
  ListenAny: "Listen to music anywhere at anytime",
  ColName: "Album Name",
  RelDate: "Release Date",
  Search: "Search...",
  homeSrchTxt: "Search your favourite artist here...",
  SearchStr: "uh-oh! No result for xyz artistname. please try something else.",
  pdHomeSrchTxt: "Search your favourite podcast here...",
  pdSearchStr:
    "uh-oh! No result for xyz podcast episode. please try something else.",
  inroTitle1: "Search your joy through music",
  inroTitle2: "Let music flow in your heart and enrich your soul",
  inroTitle3: "We Bring The Good Podcast To Life",
  SignIn: "Sign In",
  SignUp: "Sign Up",
  AlreadyRegistered: "Already Registered?",
  DontHaveAccoount: "Don't have an account?",
  Register: "Register",

  //error message
  ErrorEmail: "Email is required",
  InvalidEmail: "Invalid email",
  ErrorPassword: "Password is required",
  ErrorConfirmPassword: "Confirm Password is required",
  ErrorFirstName: "First Name is required",
  ErrorLastName: "Last Name is required",
  ErrorMinPassword: "Password should be min 6 digit",
  ErrorPasswordMatch: "Passwords did not match",
  InvalidPassword:
    "Password must be One Uppercase, One Lowercase, One Number and One Special Case Character",
  PasswordRegex:
    "/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*])(?=.{6,})/",
  EmailExist: "Email already in use.",
  SomethingWentWrong: "Something went wrong, Please try again.",
  IncorrectPassword: "Incorrect password.",
  UserNotFound: "User not found.",
};
